import type { ApplyPayload } from "./apply-schema";

export function createInitialApplyPayload(): ApplyPayload {
  return {
    insured: {
      firstName: "",
      middleName: "",
      lastName: "",
      address1: "",
      address2: "",
      city: "",
      state: "",
      zip: "",
      sex: "M",
      dob: "",
      birthStateOrCountry: "",
      email: "",
      phone: "",
      phoneType: "S",
      usCitizen: true,
      legalUsResident: false,
      felonyConviction: false,
      ssnOrTaxId: "",
      driversLicenseOrStateId: "",
      trustedContact: {
        name: "",
        address: "",
        phone: "",
        email: "",
        relationship: "",
      },
      secondaryAddressee: {
        wantsCopy: false,
        firstName: "",
        middleName: "",
        lastName: "",
        address1: "",
        address2: "",
        city: "",
        state: "",
        zip: "",
        phone: "",
      },
    },
    ownerSameAsInsured: true,
    owner: undefined,
    coverage: {
      paymentMode: "monthly",
      premiumWithApplication: "",
      faceAmount: "",
      plan: "level",
      acceptModifiedPlan: true,
      nonforfeiture: "cashSurrender",
      aplNotDesired: false,
      dividendOption: "",
      riders: {
        acceleratedDeathBenefit: false,
        grandchild: false,
        accidentalDeathBenefit: false,
        accidentalDeathFaceAmount: "",
        charitableGiving: false,
        charityName: "",
      },
      achWithdrawalDate: "",
      achWithdrawalDayOfMonth: 1,
    },
    otherInsurance: {
      hasRoyalNeighbors: false,
      rnContracts: [{}, {}],
      hasOtherCompanies: false,
      otherContracts: [{ insuranceCompany: "" }, { insuranceCompany: "" }],
      replacementDisclosure: false,
      replacementNote: "",
    },
    beneficiaries: [
      {
        role: "primary",
        firstName: "",
        middleName: "",
        lastName: "",
        address1: "",
        address2: "",
        city: "",
        state: "",
        zip: "",
        phone: "",
        email: "",
        relationship: "",
        ssnOrTaxId: "",
        dob: "",
        percent: 100,
      },
    ],
    medical: {
      q1: false,
      q2: false,
      q3: false,
      q4: false,
      q5: false,
      g6a: false,
      g6b: false,
      g6c: false,
      g6d: false,
      g6e: false,
      g6f: false,
      g6g: false,
      g6h: false,
      g6i: false,
      extraHeart: false,
      extraCancer: false,
      extraMentalHealth: false,
      extraRespiratory: false,
      extraLiverKidney: false,
      extraNeurological: false,
      q7: false,
      q8: false,
      heightFeet: 5,
      heightInches: 10,
      weightLbs: 170,
      otherHealthDetails: "",
    },
    banking: {
      bankName: "",
      routingNumber: "",
      accountNumber: "",
      accountType: "checking",
    },
    doctor: {
      firstName: "",
      lastName: "",
      city: "",
      phone: "",
    },
    employment: {
      status: "employed",
      employerName: "",
      annualSalary: "",
      jobTitle: "",
    },
    attestations: {
      accuracyConfirmed: false,
      electronicSignatureConsent: false,
      notBindingCoverage: false,
      achAuthorization: false,
      privacyAcknowledged: false,
      backupWithholdingInsured: false,
      backupWithholdingOwner: false,
      signedCity: "",
      signedState: "",
      typedSignatureInsured: "",
      typedSignatureOwner: "",
    },
    submittedAt: new Date().toISOString(),
  };
}
